cloudpilot-ai/docs

docs/tips/aws_alb_best_practice.md

doc: fix typo

---

docs/getting-started/permissions-required.mdx
sidebars.ts

doc: add privileges desc

---

docusaurus.config.ts

chore: enable edit

---

docs/changelog/changelog.mdx

doc: add CloudPilot AI v1.7.0 release doc

---

docs/karpenter/alicloud/preview/getting-started.mdx
docs/karpenter/alicloud/preview/getting-started/index.mdx
docs/karpenter/alicloud/preview/getting-started/set-up-a-cluster-and-add-karpenter/index.mdx
docs/karpenter/gcp/preview/getting-started.mdx
package-lock.json
sidebars.ts
yarn.lock

doc: initial the doc structure

doc: initial the doc structure

---

docs/karpenter/alibabacloud/preview/getting-started/index.mdx
docs/karpenter/alibabacloud/preview/getting-started/set-up-a-cluster-and-add-karpenter/index.mdx
docusaurus.config.ts
package-lock.json
yarn.lock

doc: add getting started doc

---

docs/karpenter/alibabacloud/preview/getting-started/set-up-a-cluster-and-add-karpenter/index.mdx

cleanup: update doc

---

docs/karpenter/alibabacloud/preview/getting-started/index.mdx
docs/karpenter/alibabacloud/preview/getting-started/set-up-a-cluster-and-add-karpenter/index.mdx

cleanup: make doc better

---

docs/karpenter/alibabacloud/preview/getting-started/set-up-a-cluster-and-add-karpenter/index.mdx

cleanup: fix typo

---

docs/karpenter/alibabacloud/preview/getting-started/set-up-a-cluster-and-add-karpenter/index.mdx

cleanup: use flannel cluster as demonstration

cleanup: use flannel cluster as demonstration

---

docs/karpenter/alibabacloud/v0.1/getting-started/index.mdx
docs/karpenter/alibabacloud/v0.1/getting-started/set-up-a-cluster-and-add-karpenter/index.mdx
docusaurus.config.ts
sidebars.ts

release: release karpenter alibaba cloud v0.1.0

release: release karpenter alibaba cloud v0.1.0

---

docs/changelog/1.8.0.mdx

release: add CloudPilot AI v1.8.0 release notes

release: add CloudPilot AI v1.8.0 release notes

---

docs/changelog/1.8.0.mdx

style: change style of release notes

style: change style of release notes

---

docs/karpenter/alibabacloud/v0.1/getting-started/set-up-a-cluster-and-add-karpenter/index.mdx

doc: update karpenter alibabacloud version

doc: update karpenter alibabacloud version

---

docs/getting-started/getting-started.mdx
docs/karpenter/alibabacloud/v0.1/getting-started/set-up-a-cluster-and-add-karpenter/index.mdx

feat: update doc

---

docs/tips/aws_zone_id_name_query.md
sidebars.ts

doc: add doc about zone id/name correspondence

doc: add doc about zone id/name correspondence

---

docs/getting-started/installation-environment.md
sidebars.ts

doc: Prepare the terminal environment to get started

doc: Prepare the terminal environment to get started

---

docs/karpenter/alibabacloud/v0.1/getting-started/set-up-a-cluster-and-add-karpenter/index.mdx

doc: upgrade karpenter patch version

doc: upgrade karpenter patch version

---

docs/getting-started/permissions-required.mdx

doc: add alibabacloud privilege

doc: add alibabacloud privilege

---

docs/getting-started/permissions-required.mdx

doc: add tag role

---

docs/changelog/1.9.0.mdx

doc: fix some description

---

src/content/guide/tips/aws_lb_service_accessible.mdx

doc: fix description

---

src/app/_meta.global.ts

fix: fix lint

---

src/app/_meta.global.ts
src/content/guide/getting_started/deploying_with_existing_user.mdx
src/content/guide/security/permissions_required.mdx

fix: make doc better

---

src/content/guide/getting_started/getting_started.mdx

doc: fix doc

---

src/content/guide/rebalance_configuration/workload_config.mdx

Fix `mysql` non spot friendly typo issue.
PTAL @jwcesign

fix: fix workload configuration typos.

---

src/app/_meta.global.ts
src/content/guide/security/data_collection.mdx

doc: add data collected by CloudPilot AI

doc: add data collected by CloudPilot AI

---

src/content/guide/getting_started/deploying_with_existing_user.mdx
src/content/guide/getting_started/installation_environment.mdx

Refactor the current deploying and installation doc with a formatted style.

cleanup: refactor docs with formatted style.

---

src/content/index.mdx
src/content/karpenter-alibabacloud/preview/index.mdx
src/content/karpenter-alibabacloud/v0_1/index.mdx

chore: fix link errror

---

src/content/guide/security/data_collection.mdx
src/content/guide/security/permissions_required.mdx

Refactor the security manpage with best practices and fix the nitpicking issue.

feat: adjust security guide in cloudpilot manpage.

---

src/content/guide/getting_started/getting_started.mdx

doc: polish installation doc

---

src/content/guide/index.mdx

chore: update introduction page title

chore: update introduction page title

---

src/content/guide/rebalance_configuration/workload_diversity.mdx

doc: polish workload diversity doc

doc: polish workload diversity doc

---

src/content/guide/troubleshooting/log_collection_for_troubleshooting.mdx

chore: fix typo

---

src/content/guide/getting_started/deploying_with_existing_user.mdx

chore: make style better
